const daScore = {Albania: 30,
    Armenia: 10,
    Australia: 22,
    Austria: 3,
    Azerbaijan: 27,
    Belgium: 19,
    Croatia: 11,
    Cyprus: 31,
    Czechia: 14,
    Denmark: 24,
    Estonia: 4,
    Finland: 1,
    France: 8,
    Georgia: 35,
    Germany: 17,
    Greece: 37,
    Iceland: 25,
    Ireland: 5,
    Israel: 32,
    Italy: 15,
    Latvia: 23,
    Lithuania: 18,
    Luxembourg: 33,
    Malta: 36,
    Moldova: 34,
    Netherlands: 9,
    Norway: 16,
    Poland: 26,
    Portugal: 28,
    "San Marino": 7,
    Serbia: 29,
    Slovenia: 13,
    Spain: 12,
    Sweden: 20,
    Switzerland: 2,
    Ukraine: 21,
    "United Kingdom": 6,}
export default daScore;